export const farminfo = {
  home: {
    h1: `Let Freedom Ring Farm!  Where the animals get the freedom to roam & do what they enjoy!`,
    p1: `We use The Polyface Method, also known as Regenerative Farming or Rotational Farming.  Our animals live in mobile homes with moveable fencing so that they can enjoy fresh grass while helping to fertilize the land.`,
    h2: `Come out & meet our critters!`,
    p2: `We do farm tours & believe in transparency.  Meet your future dinner & see them living their best life.  We strive for the philosophy of “One Bad Day”.  It means you love & spoil the animal until the day he or she becomes dinner.  On that day, you thank them for their sacrifice & ensure it’s as fast & painless as possible.  `,
    h3: `We are a Bio-Diverse Farm located in the Shenandoah Valley, VA.`,
    p3: `We have Cotrunix Quail, various breeds of chickens, heritage Turkeys, various duck breeds, various pig breeds, meat rabbits, various cow breeds.  `,
  },
  chickens: {
    h1: `Come meet our Layers!`,
    p1: `We have a mixed age, mixed breed flock.  These chickens wake up early each morning to hunt for bugs, eat grass, dust bathe, & explore the world around them.  We provide them with food, water, oyster shell, grit, & lots of treats.  They roam as far as they want all day, then come home to roost in their coop at night.  We make sure they are locked up safe at Sunset each day since nighttime is the most dangerous time for them.`,
    h2: `Only the best for our chickens.`,
    p2: `Happy Hens lay awesome eggs.  Plus, they are super fun to watch!  It's pretty cool to see each one develop their own personalities, likes & dislikes.  For example, some love strawberries, while others refuse to eat them.  Others prefer blueberries, others just ignore them.  Everyone loves corn, cabbage, & black fly larva.`,
    h3: `Baby Chicks are tons of fun!`,
    p3: `We prefer raising lots of small batches of chicks, that way everyone gets spoiled silly!<br>
        We make sure that our chickens get used to people & have a lot of ways to have fun.<br>
        We use Parakeet jungle gyms & toys to ensure they have plenty of mental stimulation while in the Brooder (baby pen).  Once they are grown up & outside, they have children's play-sets to play on.  Other farms may think we're silly for doing this but we enjoy being known as the best Chicken Tenders around!`,
  },
  cows: {
    h1: `Have you ever wanted to pet a cow?  Come visit!`,
    p1: `We haven't decided on a particular breed just yet.  We love heritage breeds & conservation so figuring out the right one for us may take some time with all the options.  Currently, we have Jenny the Jersey Cow, she's our herd matriarch.  Next is Lilly the Dexter Cow.  Then we have Cookie the we-don't-know Cow.  Cookie & Bubba are in the picture above.  Shania is a Beef Shorthorn. Charlene is a Charolais. Patty is a White Park.  Bailey is a British White. Baby Cow is an Angus.`,
    h2: `The cows have us well trained, meaning: we always have treats in our pockets!`,
    p2: `We use horse treats & Alfalfa Cubes for spoiling our Grass Dogs (cows).  They all enjoy chin & chest scratches too!  We are big on positive reinforcement & feel that everyone should be treated with love. `,
    h3: `We love cows & know you will too, once you meet them!`,
    p3: `Did you know that cows don't have top teeth in the front of their mouth?  They do have super scratchy tongues, just like cats.  Come learn all about them in person!`,
  },
  ducks: {
    h1: `Come meet our Quack Pack & Quacker Jacks!`,
    p1: `Ducks are hard not to love.`,
    h2: `These are our Cayuga Ducks.`,
    p2: `These naughty little Quackers broke into our pool this Winter to have a swim on a nice day.`,
    h3: `We raised ducks until a Broody Hen decided she wanted to!`,
    p3: `Ducklings are terribly messy, good thing they're so cute!  We were cleaning the Brooder (baby pen) every day, sometimes twice a day depending on how crazy they got.  They are very soft, sweet, & cute…but man, did that get old quick.  So when Belle (one of our chickens), went Broody we decided to get her some duck eggs to hatch.  She was a great duck mom, although she was shocked when they started swimming one day!`,
  },
  eggs: {
    h1: `Here's a good place to get Eggucated.`,
    p1: `You can buy Quail eggs, Chicken Eggs, & Duck Eggs from us!  Availability will be impacted by a number of factors including, but not limited to: time of year, weather, predator activity, & introduction of new layers.`,
    h2: `What makes our eggs special:`,
    p2: `Most farms raise their chickens inside big houses.  The chickens never get to see the light of day, just light bulbs.  Every aspect of the chicken's life is carefully controlled to maximize egg laying potential.  At 18 months old, they get rid of their laying hens & get new ones.

        On our farm, we let Mother Nature do her natural thing.  We put our chickens health & happiness first, our profits come second.`,
    h3: `Egg Facts:`,
    p3: `<b>When:</b> Chickens start laying eggs when they hit puberty, on average that's around 6 months old.  Smaller chickens, like Leghorns, usually start laying around 4 months old.  Larger chickens, like Brahmas, start laying around 8 months old.  There is a drop in egg laying at a year old, then there is a substantial drop off in laying at 18 months.  That's when commercial egg farms get rid of their laying hens & get a new batch.<br><br>
        <b>Eggs are not baby chickens.</b>  They are Ova, no different than a human female's period.  In chickens, an Ova is released every 25 hours of daylight.  In humans, it's roughly once every 21 days.  So in the Summer months, when there are longer days, chickens lay a lot more eggs.  While in the Winter, chickens lay far less eggs due to lack on daylight.  Commercial chicken farms get around this by controlling the light in the chickens houses.<br><br>
        <b>Eggs come in a variety of colors!</b>  The color of the egg is dictated by the breed of chicken.  You may only be familiar with white or brown eggs from the grocery store, here's why:  White Eggs form the grocery store come from White Leghorns.  They are the top egg laying breed, in fact, they hold the world record for eggs laid on consecutive days.  The brown eggs in the grocery store come from ISA Browns.  They are the second best breed for egg laying.  The chickens that lay the fun colored eggs don't lay as many.  So economically speaking, those breeds aren't as profitable to keep around.<br>
        <b>Stress reduces laying.</b>  Things that stress chickens include but are not limited to: meeting new chickens because it upsets the pecking order, a change in routine, predators coming around, change in diet, bad weather (only if you have your hens on pasture).  When it's too hot out, the chicken's body is more focused on cooling off instead of egg laying.  When it's too cold, the chicken's body is more focused on staying warm instead of egg laying.  Commercial egg farms control the temperature in the hen houses.  Since our hens are on pasture, we give our chickens cold treats (like frozen fruit) in the Summer & warm treats (like oatmeal) & warm water in the Winter.  They always have to option of going inside their coop (house) as they so choose.<br><br>
        <b>No Boys allowed!</b>  Most farms don't bother having a Rooster (male chicken) because you only need them if you want baby chickens.  Chickens lay eggs due to daylight, males aren't needed for that.  Don't get me wrong, Roosters can be helpful in protecting chickens that are out on pasture.  But most farms don't put chickens on pasture & they aren't going to feed a Rooster for no good reason.  If you've ever seen a video where someone goes to the grocery store, buys eggs, & hatches them at home; please know that video totally lied to you.  Also, if you've seen the videos where someone hatches eggs by carrying them around in their bra, that's also a lie.  Eggs need a very specific humidity, temperature, & rotation schedule that the human body wouldn't be able to do.  If you buy eggs from a small farm, they may or may not have a Rooster.  You can tell if an egg was fertilized if there is a bullseye in the yolk.<br><br>
        <b>What's in an Egg?</b>  A Quail Egg is different than a Chicken Egg, both are different than Duck Eggs, not just in size but in nutrients & cholesterol levels as well.  Different kinds of eggs have different protein structures.  This is important to know when using eggs.  For example, Duck Eggs have less water content & higher fat content than Chickens Eggs.  This makes Duck Eggs superior for baking but not as good for scrambling or frying.<br><br>
        <b>The Float Test:</b>  The Float Test is when you place an uncooked egg in a glass or bowl of water to see if it floats.  This can tell you the general age of the egg.  It can NOT tell you if an egg is safe to eat.  When an egg is laid, there is a wee air bubble in there.  Egg shells are porous.  So as the egg ages, water inside the egg evaporates & the air bubble grows larger.  The more the egg floats, the older it is.  The Float Test can NOT tell you if dangerous pathogens have entered the shell.  That is an old wives tale.<br><br>
        <b>Why Store Bought Eggs are Easier to Peel:</b>  Legally speaking, a farm has 30 days to get the eggs off of the property.  Legally speaking, a grocery store then has 30 days to sell the eggs.  So when you buy eggs at the store, they can be up to 60 days old.  Buying directly from a farmer cuts out the middle man & gets them to you faster.  Check the side of your egg carton.  There is a three digit number, 001-365.  That number tells you the day of the year your eggs were laid on: 001 is January 1st while 365 is December 31st,  It also has a Best By Date.  Best By means exactly that.  The eggs don't expire on that date, they just can't be guaranteed to be as perfect as they once were.<br><br>
        <b>Storing Eggs:</b>  In the EU, the government mandates that all chickens be vaccinated against Salmonella.  They do not wash their eggs, therefore, the eggs can be stored at room temperature.  In the US, the government mandates that all eggs be washed before they are sold to avoid Salmonella.  Washing eggs removes the Bloom.  The Bloom is a clear antimicrobial coating that is the very last thing that happens to the egg as it's laid.  Removing the Bloom opens the pores of the eggs shell so you must refrigerate eggs after washing.  Random tidbit for you:  Fat absorbs odors.  So store your eggs & cheese as far from cut onions or smelly food as you can.<br><br>
        <b>How Will I know if an egg has gone bad?</b> Short answer is: your nose.  When you open your refrigerator door a really bad smell is going to hit you.  Like a mix of sulfur & death.  When you get close to the egg carton, that smell will intensify in a way you didn't know was possible.  When you open that egg carton it will smell like Satan himself took a big ‘ole dump in there.  If you're silly enough to want to crack open that egg, do it outside or the smell will permeate your house for a week.  Inside the egg will be black & purple & the smell will make you gag or toss your cookies.  Eggs go rotten when the air bubble touches the yolk.  Eggs are stored pointy end down to give you as much time possible before the air touches the yolk.  I kept a carton of eggs in the back of my college fridge for a year to learn this the hard way so you don't have to.  You're welcome.<br><br>
        <b>Eggs are one of the 8 Major Allergens.</b>  You can be allergic to Chicken Eggs but be fine with Duck Eggs (like the actress Margot Robbie).  You can be fine with Chicken Eggs but have a Duck Egg allergy.  The most common allergic reaction to eggs is Gastrointestinal Distress (stomach cramping, vomiting, diarrhea).`,
  },
  events: {
    h1: `Look for us at Farmer's Markets!`,
    p1: `We'll be at the Mount Jackson Farmer's Market the first Saturday of the month & DOTS Farmer's Market every other Saturday.`,
    h2: `The Cows just got their yearly check up.`,
    p2: `Just like humans, cows need annual check ups.  It's helps to catch problems early!  Everyone got a clean bill of health!!Shania the Beef Shorthorn is pictured in our head-chute.`,
    h3: `Our Geese are Broody`,
    p3: `We are hoping they hatch babies but they don't seem to be very good at this whole “sitting on the eggs” things so…we'll see what happens.  This is Emmy taking her turn on the nest.`,
    h4: `We have lots of baby Bun-Buns right now.`,
    p4: `We sell live rabbits & processed rabbits.  Whether you’re looking for a new pet or pet food, we’ve got you covered.`,
  },
  farmers: {
    h1: `Brian & Liz`,
    p1: `Brian & Liz grew up in the same neighborhood.  As young children, Brian's sister & Liz were friends & Brian's mom was Liz's Brownie leader.  Both Brian & Liz left for college, then returned to the same neighborhood after college.  In a weird twist of fate, Brian bought a house that used to belong to Liz's grandparents…4 streets down from Liz's parents house.  They lived 4 streets apart for 4 years…both walking in the neighborhood, running in the neighborhood, & walking their dogs in the neighborhood on a daily basis.  They finally bumped into each other one night as Brian was jogging & Liz was walking her dog.  They talked for a bit, then Liz asked for Brian's phone number to arrange for a puppy play date at a later time.  They quickly became connected at the hip.<br><br>
        Brian worked from home while Liz commuted into DC.  They were mostly happy with life but never felt at home in the city.  In fact, they used any excuse to escape - mentally or physically.  They traveled every weekend, played on 2 co-ed soccer teams, took every cooking class they could find, did a lot of work with homeless people, did animal rescue, & were always out with friends.  After getting married, they decided they needed a change of scenery.  Brian's family owned a farm that wasn't being used & Liz's family had farming in the blood going back generations.  It seemed like a logical fit for them to try their hand at something new.<br><br>
        They moved out to the farm & wasted no time in becoming members of the community.  They joined the Lion's Club, a church, started volunteering for a number of charity programs, & became Foster Parents.  They also slowly started getting into farming, one animal at a time as they continued doing animal rescue.  With the farm growing, their responsibilities grew & they slowly had to step back from all the charity work they were doing.  They still do animal rescue & are active in the Lion's Club.`,
    h2: `Brian`,
    p2: `Poor Brian gets to do most of the heavy lifting.  Who needs a gym when you've got 50lbs bags or feed & 40lb water buckets multiple times a day?  After working with computers for years, Brian hates them.  So far, he has loved every animal on the farm except turkeys.`,
    h3: `Liz`,
    p3: `Liz has been an EMT since she was 21.  She used to work for a 3 letter agency in DC so please don't bring up politics, she quite had her fill.  After learning that she had a Soy Allergy (one of the 8 Major Allergens), she took her love of cooking & baking to a whole new level.  She does everything from scratch, the same as her grandparents did but with a modern twist.  She is loving life as a Farmer & Chef.  Below are some pictures of her ancestors farming & a picture of her with a rescue kitten, just after feeding the little guy.`,
  },
  pigs: {
    h1: `Pigs A.K.A. Bacon Seeds`,
    p1: `We have raised a few different breeds of Swine to help us figure out what personality traits we prefer & what body types we prefer.  First, we had to decide if we wanted Bacon Pigs or Lard Pigs.  Bacon Pigs are long, lean, & get big fast.  They give you a lot of meat & great bacon.  But…big pigs are more dangerous than small pigs & Bacon Pigs tend to get aggressive as they get older.  Lard Pigs are generally small, very round, & have way more lard than Bacon Pigs.  In our experience, they are also sweeter & more docile.  So no breed is perfect & you have to live & learn.  In the picture above: the black pig is named Keven Bacon (we name all of our male pigs that).  He is an American Guinea Hog, which is a Lard Pig.  The 2 tan looking pigs are Gladys & Tammy.  They are Gloucester Old Spot - Tamworth pigs, which are 2 different breeds of Bacon Pig.  We were hoping they would be able to cross breed & make us babies somewhere in between their sizes & temperaments.  Sadly, that didn't work out.  We have had some Oassabaw Island Hogs & Mulefoot Pigs at other times.  Mulefoot has been our favorite so far.`,
    h2: `Did you know that pigs come in different breeds, sizes, & colors?`,
    p2: `The Oinks in this picture are a cross between Yorkshire & <a href="https://ossabawisland.org/island/ossabaw-pigs/">Ossabaws</a>.  The orange one was Kevin Bacon, Black was the black one, Runty was the pink & gray one, & Pink was the pink & orange one.  This was our first ever round of pigs.  It was a lot of fun watching them grow, getting to know their personalities, & spoiling them with treats.`,
    h3: `Happy Oinks`,
    p3: `We move our pigs to fresh grass after they rip up the weeds & air rate the ground for us.  After they are moved to a fresh spot, we throw grass seed down to help make things tasty for the cows that will come along later.  NPK (Nitrogen, Phosphorus, & Potassium) are the main 3 things needed for healthy plant growth.  Pig poop is high in Phosphorus so they help our soil health in more than one way.`,
  },
  quail: {
    h1: `Quail, tiny but awesome.`,
    p1: `The picture above is 2 female Coturnix Quail enjoying a dust bath.  When we first moved out to the farm, we wanted to start with something easy.  Coturnix Quail fit the bill.  There weren't a lot of resources on raising them in the manor we wanted to so it was quite the learning experience!  Most farms raise them in a very short cage because if they get scared, they shoot straight up in the air.  The short cage doesn't allow them enough room to build up enough speed to break their necks.  We chose to go with a 6 foot tall enclosure that had netting at the top to help soften any impact they may have.  We put panels around the sides so that they can't see scary things & predators can't see them.  Calm birds, are happy birds.  Coturnix Quail hit puberty at 8 weeks old, that means the girls start laying eggs & the boys get crazy violent unless you have the proper breeding ratios.  So that's when the boys go to Freezer Camp.`,
    h2: `This is our mobile Quail House.`,
    p2: `This allows our quail to enjoy fresh grass, clean air, & live life to the fullest while not seeing or being seen by predators.  The panels all around the bottom prevent coyotes, foxes, & other predators from being able to dig under the walls.  The roof & hardware cloth walls keep them safe from owls & hawks.  Inside they have lots of little guinea pig houses to hide in, a big comfortable coop to enjoy, dust baths, & all the necessities for life (food, water, grit, oyster shell, & tons of treats).`,
    h3: `Raising Quail`,
    p3: `Baby birds are a lot like baby humans, they can't control their body temperature or clean up after themselves.  It's our job as care takers to ensure that their every need is met.  Food, water, & butts must be watched closely, especially that first week of life.  They can get stuck in the feeders if the food gets too low.  They can drowned or get hypothermia if they fall in their water dish, we put marbles in the water dish to help prevent that.  You have to check them for Paste Butt frequently (it's when their poo glues their butthole shut, then the waste backs up inside of them & they die).  That's right, raising birds includes a fair amount of butt wiping.  Fun times.<br><br>
        As chicks (babies), we provide heat plates for them because it's the closest thing to a mom that we can provide.  Some people prefer to use heat lamps due to it costing less.  We personally don't feel like that's a good choice for us due to the fire risk.  We choose to put toys in the Brooder (baby pen) because we feel that it's healthier for their mental & emotional development.  Once they are old enough, we give them field trips outside so that they can get used to their future home.  Then, when they are fully feathered out, they move to their mobile coop & run set up.`,
  },
  rabbits: {
    h1: `Meat Rabbits A.K.A. Bun-Buns`,
    p1: `Rabbits provide a very healthy lean meat & are fairly easy to keep.  We had hoped to raise purebred Silver Fox Rabbits but they are proving quite difficult to get a hold of.  So we have expanded our rabbitry to include Chinchilla Rabbits as well.`,
    h2: `Coco is on the left, Chocolate Chunk is on the right.`,
    p2: `Both of these ladies are Chocolate Silver Fox Rabbits.  They were the first Buns on the farm.`,
    h3: `Bun-Buns on the farm:`,
    p3: `As you can see from the pictures below, we're big on spoiling around here.  We make sure our Buns get lots of greens to nibble on for their physical health & their entertainment.  They also get toys & things to chew on since they aren't ok with having their teeth brushed!  These guys are the one exception to our mobile pasture setup.  For a few reasons.  First, predators.  Until we can guarantee their safety in the field, we won't put them in harms way.  Second is health.  Buns need to stay dry, not too hot, & not too cold.  So we're looking at various building options.  Third but most important is disease.  Putting them in the grass poses a risk that they might catch a disease from the wild rabbits that live here.  We try to take them outside for field trips as often as possible as a compromise.`,
  },
  turkeys: {
    h1: `Our Turkeys A.K.A The Snood Brood`,
    p1: `Our turkeys got to run around & cause trouble all day every day.  Seriously, some trouble.  These not so little jerks ran around stealing other animals food even though they had their own to eat.  Sometimes, they would take a break & sit in our rocking chairs.  Other times, they would jump on our cars, looking for a way to break in & go joy riding.  They enjoyed following us around while we did chores, randomly yelling that we were doing it wrong.  One time, they even walked up the street to go talk to our neighbor!`,
    h2: `Did you know there are all sort of different Turkey Breeds & colors?`,
    p2: `For our first go at Turkeys, most were sold out (thanks 2020) so we weren't able to try as many different breeds as we would have liked.  We got Royal Palms, Blue Slates, & 2 Broad Breasted Bronze.  After raising Quail & Chickens, we felt ready for turkeys even though we knew that they have a high mortality rate in the Brooder (baby pen).  It was still pretty crazy despite tons of research.  They are like little fluffy turtles as babies.  If they fall over on their backs, they can't get back up.  So we started calling them Flurtles, short for Fluffy Turtles.  It was both heart breaking & frustrating every time one passed away for no reason.  Thankfully, 17 made it to adulthood.  This is them as teenagers in the grown out pen.`,
    h3: `Turkeys make for terrible supervisors, no matter what they may tell you…`,
    p3: `Time to move the chickens or ducks?  Turkeys are there to supervise you.  Baby chicken got out of the fence & can't figure out how to get back in due to panic?  Turkeys will chase both of you while yelling!  Because that totally helps…`,
  },
};
